# @name find-many-clients
GET http://localhost:3333/findManyCliente

###

# @name search-all-cities
GET http://localhost:3333/searchAllCities

###

# @name city-internet-status
GET http://localhost:3333/cityInternetStatus/LINHARES

###

# @name general-internet-status
GET http://localhost:3333/generalInternetStatus

###

# @name internet-status-by-hub
GET http://localhost:3333/internetStatusByHub/Concentrador_Giganet

