# @name find-many-clients
GET http://localhost:3333/findManyCliente

###

# @name search-all-cities
GET http://localhost:3333/searchAllCities

###

# @name city-internet-status
GET http://localhost:3333/cityInternetStatus/SOORETAMA

###

# @name general-internet-status
GET http://localhost:3333/generalInternetStatus

###

# @name internet-status-by-hub
GET http://localhost:3333/internetStatusByHub/Concentrador_Core

###

# @name search-all-hubs
GET http://localhost:3333/searchAllHubs

###

# @name internet-status-by-pop-cliente
GET http://localhost:3333/internetStatusByPopCliente/SOORETAMA B

###

# @name search-all-pop-clientes
GET http://localhost:3333/searchAllPopClientes

###

# @name most-common-plan
GET http://localhost:3333/mostCommonPlan

###

# @name most-common-city
GET http://localhost:3333/mostCommonCity

###

# @name average-time-connected
GET http://localhost:3333/averageTimeConnected




